### ISSUE TITLE
insert.js:  cannot read property of undefined

### ISSUE THREAD

**Issue by srl295** [kuroljov/pino-mongodb#1]
in `lib/insert.js` -  `this.program.showInsertErrors` does not work because `this` is scoped to `function insertOne()`. 

Might work around with `const that = this;` at the top of the line. Or using `bind`.

**Comment by Kuroljov** [comment]
Thanks. That was my bad. I will patch it soon

**Comment by kuroljov** [comment]
Master branch now contains the next version. I will close this issue and move project to the `pino` organization
