### ISSUE TITLE
readline fails with pipe

### ISSUE THREAD

**Issue by srl295** [kuroljov/pino-mongodb#2]
See: https://github.com/nodejs/node-v0.x-archive/issues/1742#issuecomment-2146350 - the `readline` module might not be the right choice here.

**Comment by Kuroljov** [comment]
Alright I will use `node-bufferstream` instead

**Comment by kuroljov** [comment]
Master branch now contains the next version. I will close this issue and move project to the `pino` organization

**Comment by srl295** [comment]
I ended up using carrier as per [this comment](https://github.com/nodejs/node-v0.x-archive/issues/1742#issuecomment-2146350)  for [pino-couch](https://github.com/IBM/pino-couch/) which by the way is based off pino-mongodb! See [blog post](https://srl295.github.io/2017/06/02/pino-couch/)
